### ISSUE TITLE
A way to know all diverse characterstics for making images them

### ISSUE THREAD

**Issue by jairajsahgal** [multiavatar/multiavatar-python#1]
Can you please all the diverse characterstics that can be used to combine and make random characters?

**Comment by giekaton** [comment]
There are 16 initial characters and 3 different color themes/versions. So in total there are 16 x 3 = 48 initial source characters from which all avatars are generated. You can see these initial characters by opening the `index.html` file in your browser. This `index.html` file can be found in the `Multiavatar in JavaScript` repository here: https://github.com/multiavatar/Multiavatar/blob/main/svg/index.html

**Comment by jairajsahgal** [comment]
figured it out
I have to just enter any random string
